name: hello_world
description: A new Flutter project.

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter: 
    sdk: flutter 

  cupertino_icons: ^0.1.2
  flutter_sound: ^1.3.5
  webfeed: ^0.4.2
  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/song.mp3
    
